### ISSUE TITLE
Nested attributes stopped working

### ISSUE THREAD

**Issue by dnesteryuk** [rom-rb/rom#78]
It worked fine with Rom 0.4.1 and it stopped working with Rom 0.4.2 (code from master doesn't work either for this purpose).

Example:

``` ruby
setup.schema do
      base_relation(:users) do
        repository :default

        attribute 'name'
        attribute 'email'
        attribute 'roles'
      end
    end

    setup.mappers do
      define(:users) do
        model name: 'User'

        attribute :name
        attribute :email

        group 'roles' do
          attribute 'role_name'
        end
      end
    end
```

The expected response:

```
users:
  - name: 'Jane'
    email: 'jane@doe.org'
    roles:
      - role_name: 'Member'
      - role_name: 'Admin'
```

This code returns nil

``` ruby
      jane = rom.read(:users).by_name('Jane').to_a.first
      expect(jane.roles.length).to eql(2)  # roles are nil here
```
